---
- name: Create .functions directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.functions"
    state: directory

- name: Copy switch-project files to .functions directory
  copy:
    src: switch_project_function.sh
    dest: "{{ lookup('env', 'HOME') }}/.functions/"

- name: Copy switch-project python files to .functions directory and make executable
  copy:
    src: switch_project.py
    dest: "{{ lookup('env', 'HOME') }}/.functions/"
    mode: ug+rx
