---
- name: Create .functions directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.functions"
    state: directory

- name: Copy switch-project files to .functions directory
  copy:
    src: switch_project_function.sh
    dest: "{{ lookup('env', 'HOME') }}/.functions/"

- name: Add source .functions to .zshrc
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    regexp: "^for bash_function in ~/.functions/"
    line: "for bash_function in ~/.functions/**/*.sh; do source $bash_function; echo $bash_function; done"

- name: Copy switch-project python files to .functions directory and make executable
  copy:
    src: switch_project.py
    dest: "{{ lookup('env', 'HOME') }}/.functions/"
    mode: ug+rx

- name: Add putting .functions on PATH in .zshrc so that python script can be found in any directory
  lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    regexp: '^export PATH=\"\$PATH\:\$HOME/.functions/\"'
    line: 'export PATH="$PATH:$HOME/.functions/"'